-- =========================================================
-- support_tickets_db schema
-- =========================================================
DROP TABLE IF EXISTS tickets;

CREATE TABLE tickets (
    ticket_id           SERIAL PRIMARY KEY,
    domain              TEXT NOT NULL DEFAULT 'ecommerce',
    title               TEXT NOT NULL,
    description         TEXT NOT NULL,
    resolution_notes    TEXT,
    status              TEXT NOT NULL,        -- open / in_progress / resolved / closed
    priority            TEXT NOT NULL,        -- low / medium / high / critical
    category            TEXT NOT NULL,        -- refund / shipping / damaged_item / wrong_item / account / payment
    assignee            TEXT,
    reporter            TEXT,
    carrier             TEXT,                 -- FedEx / UPS / USPS / DHL
    tracking_number     TEXT,
    shipping_status     TEXT,                 -- in_transit / delayed / delivered / lost
    estimated_delivery  DATE,
    order_id            TEXT,
    created_at          TIMESTAMP NOT NULL,
    resolved_at         TIMESTAMP,
    metadata            JSONB
);

-- Helpful indexes for the SQL side of your RAG+SQL queries
CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_tickets_category ON tickets(category);
CREATE INDEX idx_tickets_created_at ON tickets(created_at);

-- =========================================================
-- Dummy data: 80 realistic e-commerce electronics support tickets
-- =========================================================

INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my wireless headphones three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', NULL, 'in_progress', 'low', 'refund', 'Marcus Reed', 'customer_2679', NULL, NULL, NULL, NULL, 'ORD-809570', '2026-06-13 10:54:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Unable to update saved payment method', 'I''m trying to remove an old expired card and add a new one under my payment settings, but the page just spins and never saves the change.', NULL, 'open', 'low', 'account', 'Diego Torres', 'customer_9279', NULL, NULL, NULL, NULL, 'ORD-731262', '2026-08-17 20:19:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my 4K action camera.', NULL, 'in_progress', 'medium', 'account', 'Priya Nair', 'customer_1106', NULL, NULL, NULL, NULL, 'ORD-895667', '2026-07-31 15:04:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a external SSD and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'open', 'low', 'wrong_item', NULL, 'customer_2674', NULL, NULL, NULL, NULL, 'ORD-197251', '2026-07-04 10:09:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Can''t log into my account after password reset', 'I requested a password reset for my account, followed the email link, set a new password, but now I get an ''invalid credentials'' error every time I try to log in.', NULL, 'open', 'high', 'account', 'Marcus Reed', 'customer_7201', NULL, NULL, NULL, NULL, 'ORD-182627', '2026-06-12 03:38:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Can''t log into my account after password reset', 'I requested a password reset for my account, followed the email link, set a new password, but now I get an ''invalid credentials'' error every time I try to log in.', NULL, 'open', 'low', 'account', 'Diego Torres', 'customer_5741', NULL, NULL, NULL, NULL, 'ORD-183667', '2026-07-23 10:07:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my portable power bank but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'in_progress', 'low', 'damaged_item', 'Priya Nair', 'customer_4432', NULL, NULL, NULL, NULL, 'ORD-802729', '2026-07-17 14:32:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my smartwatch has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Reset the account manually on the backend and restored access; recommended customer clear browser cache.', 'resolved', 'high', 'shipping', 'Marcus Reed', 'customer_8573', 'FedEx', 'FE6649827836', 'delivered', '2026-07-19', 'ORD-497887', '2026-07-17 16:47:32', '2026-07-26 19:47:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Item arrived with a cracked screen', 'The tablet stand I ordered arrived with a visible crack across the display. The box itself looked fine on the outside, so I think it may have been packaged damaged, not damaged in transit.', NULL, 'in_progress', 'medium', 'damaged_item', 'Diego Torres', 'customer_8517', NULL, NULL, NULL, NULL, 'ORD-249811', '2026-07-19 09:16:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my external SSD.', 'Issued a full refund to the original payment method after confirming the return was received in warehouse.', 'closed', 'medium', 'account', 'Aisha Bello', 'customer_7543', NULL, NULL, NULL, NULL, 'ORD-479580', '2026-07-24 08:59:32', '2026-08-01 09:59:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my gaming mouse three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', NULL, 'open', 'high', 'refund', NULL, 'customer_2040', NULL, NULL, NULL, NULL, 'ORD-503457', '2026-07-03 18:02:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Promo code discount didn''t apply at checkout', 'I used the promo code from your newsletter when ordering my external SSD, but the final charge doesn''t reflect any discount at all.', 'Escalated to the payment processor; duplicate charge was reversed within 3 business days.', 'resolved', 'high', 'payment', 'Sarah Chen', 'customer_2876', NULL, NULL, NULL, NULL, 'ORD-814825', '2026-06-14 04:42:32', '2026-06-20 05:42:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Unable to update saved payment method', 'I''m trying to remove an old expired card and add a new one under my payment settings, but the page just spins and never saves the change.', 'Escalated to the payment processor; duplicate charge was reversed within 3 business days.', 'resolved', 'low', 'account', NULL, 'customer_5315', NULL, NULL, NULL, NULL, 'ORD-624902', '2026-07-29 20:33:32', '2026-08-01 06:33:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Promo code discount didn''t apply at checkout', 'I used the promo code from your newsletter when ordering my bluetooth speaker, but the final charge doesn''t reflect any discount at all.', NULL, 'open', 'medium', 'payment', 'Priya Nair', 'customer_9837', NULL, NULL, NULL, NULL, 'ORD-916449', '2026-06-15 12:53:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a smart home hub and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'open', 'low', 'wrong_item', NULL, 'customer_6038', NULL, NULL, NULL, NULL, 'ORD-351083', '2026-08-14 05:35:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my mechanical keyboard has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Sent the correct color/item via next-day shipping and provided a prepaid return label for the incorrect item.', 'resolved', 'high', 'shipping', 'Aisha Bello', 'customer_3060', 'UPS', 'UP3962958940', 'delivered', '2026-06-02', 'ORD-234628', '2026-05-28 21:56:32', '2026-06-01 01:56:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Can''t log into my account after password reset', 'I requested a password reset for my account, followed the email link, set a new password, but now I get an ''invalid credentials'' error every time I try to log in.', 'Applied the missing discount manually and refunded the difference to the customer''s card.', 'resolved', 'medium', 'account', 'Marcus Reed', 'customer_4681', NULL, NULL, NULL, NULL, 'ORD-167136', '2026-07-09 12:54:32', '2026-07-18 15:54:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Order hasn''t arrived, tracking shows no movement', 'I ordered a mechanical keyboard 9 days ago and the tracking page has shown ''label created'' with no update since. Estimated delivery date already passed. Can someone check what''s going on?', NULL, 'open', 'low', 'shipping', 'Sarah Chen', 'customer_6413', 'DHL', 'DH3030106617', 'lost', '2026-06-22', 'ORD-174299', '2026-06-17 06:14:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Item arrived with a cracked screen', 'The laptop charger I ordered arrived with a visible crack across the display. The box itself looked fine on the outside, so I think it may have been packaged damaged, not damaged in transit.', NULL, 'open', 'medium', 'damaged_item', NULL, 'customer_7939', NULL, NULL, NULL, NULL, 'ORD-531071', '2026-06-22 14:28:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my 27-inch monitor three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', 'Corrected the shipping address in our system before the label was generated; delivery proceeded normally.', 'resolved', 'high', 'refund', 'Sarah Chen', 'customer_5073', NULL, NULL, NULL, NULL, 'ORD-300896', '2026-07-27 20:03:32', '2026-07-31 02:03:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my portable power bank but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'in_progress', 'high', 'damaged_item', 'Sarah Chen', 'customer_8260', NULL, NULL, NULL, NULL, 'ORD-947272', '2026-06-12 10:28:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my wireless headphones.', NULL, 'open', 'critical', 'account', 'Diego Torres', 'customer_3724', NULL, NULL, NULL, NULL, 'ORD-526156', '2026-06-19 22:18:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Two accounts got merged, order history missing', 'Something happened during checkout and now I only see one of my two account''s order histories. My 27-inch monitor order from last month has disappeared from my account page.', NULL, 'open', 'medium', 'account', NULL, 'customer_5345', NULL, NULL, NULL, NULL, 'ORD-922157', '2026-06-24 04:04:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my smart home hub.', NULL, 'open', 'low', 'account', 'Diego Torres', 'customer_1958', NULL, NULL, NULL, NULL, 'ORD-707314', '2026-06-13 11:44:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a 27-inch monitor and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'open', 'medium', 'wrong_item', 'Priya Nair', 'customer_1931', NULL, NULL, NULL, NULL, 'ORD-632496', '2026-08-11 08:27:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my webcam has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Reset the account manually on the backend and restored access; recommended customer clear browser cache.', 'resolved', 'low', 'shipping', 'Aisha Bello', 'customer_5033', 'USPS', 'US8370987661', 'delayed', '2026-06-10', 'ORD-707040', '2026-06-06 11:52:32', '2026-06-08 17:52:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Two accounts got merged, order history missing', 'Something happened during checkout and now I only see one of my two account''s order histories. My gaming mouse order from last month has disappeared from my account page.', NULL, 'in_progress', 'medium', 'account', 'Sarah Chen', 'customer_1152', NULL, NULL, NULL, NULL, 'ORD-580547', '2026-06-02 19:25:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my bluetooth speaker has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Escalated to the payment processor; duplicate charge was reversed within 3 business days.', 'resolved', 'low', 'shipping', 'Priya Nair', 'customer_2127', 'FedEx', 'FE7676965974', 'in_transit', '2026-07-08', 'ORD-356150', '2026-07-05 04:21:32', '2026-07-13 12:21:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my laptop charger but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'high', 'damaged_item', 'Priya Nair', 'customer_5462', NULL, NULL, NULL, NULL, 'ORD-395442', '2026-06-05 06:46:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a bluetooth speaker and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'in_progress', 'medium', 'wrong_item', 'Priya Nair', 'customer_1832', NULL, NULL, NULL, NULL, 'ORD-196781', '2026-05-31 23:38:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my 27-inch monitor but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'medium', 'damaged_item', 'Priya Nair', 'customer_5291', NULL, NULL, NULL, NULL, 'ORD-269430', '2026-06-25 19:46:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Unable to update saved payment method', 'I''m trying to remove an old expired card and add a new one under my payment settings, but the page just spins and never saves the change.', NULL, 'open', 'low', 'account', 'Priya Nair', 'customer_9938', NULL, NULL, NULL, NULL, 'ORD-137778', '2026-07-04 18:56:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Requesting refund instead of replacement', 'My 4K action camera arrived defective and I initially asked for a replacement, but I''ve decided I''d rather just get a refund at this point. How do I change the request?', NULL, 'open', 'low', 'refund', NULL, 'customer_1653', NULL, NULL, NULL, NULL, 'ORD-475190', '2026-07-25 16:16:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my noise-cancelling earbuds three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', 'Corrected the shipping address in our system before the label was generated; delivery proceeded normally.', 'resolved', 'high', 'refund', 'Diego Torres', 'customer_3532', NULL, NULL, NULL, NULL, 'ORD-348237', '2026-08-01 07:35:32', '2026-08-08 07:35:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a 4K action camera and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'in_progress', 'low', 'wrong_item', NULL, 'customer_2771', NULL, NULL, NULL, NULL, 'ORD-501124', '2026-08-16 22:17:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Item arrived with a cracked screen', 'The portable power bank I ordered arrived with a visible crack across the display. The box itself looked fine on the outside, so I think it may have been packaged damaged, not damaged in transit.', NULL, 'in_progress', 'medium', 'damaged_item', 'Marcus Reed', 'customer_4652', NULL, NULL, NULL, NULL, 'ORD-124813', '2026-05-29 07:06:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a external SSD and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', NULL, 'open', 'critical', 'wrong_item', 'Aisha Bello', 'customer_6753', NULL, NULL, NULL, NULL, 'ORD-772642', '2026-06-17 00:48:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my tablet stand.', NULL, 'open', 'low', 'account', 'Aisha Bello', 'customer_3925', NULL, NULL, NULL, NULL, 'ORD-708792', '2026-07-19 12:25:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Unable to update saved payment method', 'I''m trying to remove an old expired card and add a new one under my payment settings, but the page just spins and never saves the change.', NULL, 'in_progress', 'medium', 'account', 'Aisha Bello', 'customer_2894', NULL, NULL, NULL, NULL, 'ORD-503906', '2026-06-09 07:15:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Package marked delivered but never received', 'Tracking says my 4K action camera was delivered yesterday afternoon, but there''s nothing at my door or with my neighbors. I checked all around the property. This is concerning since it''s a higher-value item.', NULL, 'open', 'medium', 'shipping', 'Diego Torres', 'customer_6967', 'USPS', 'US7971399399', 'in_transit', '2026-08-19', 'ORD-552248', '2026-08-12 15:33:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Received the wrong color', 'I ordered the black version of the USB-C hub but received the white one instead. Could I get the correct color sent, and how do I return the incorrect item?', 'Corrected the shipping address in our system before the label was generated; delivery proceeded normally.', 'resolved', 'medium', 'wrong_item', NULL, 'customer_5844', NULL, NULL, NULL, NULL, 'ORD-681343', '2026-08-05 07:05:32', '2026-08-12 17:05:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Received the wrong color', 'I ordered the black version of the gaming laptop but received the white one instead. Could I get the correct color sent, and how do I return the incorrect item?', NULL, 'resolved', 'high', 'wrong_item', 'Priya Nair', 'customer_5700', NULL, NULL, NULL, NULL, 'ORD-320392', '2026-06-26 18:53:32', '2026-07-03 01:53:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Charged twice for the same order', 'I can see two identical charges on my card for the same bluetooth speaker order placed yesterday. Only one order confirmation email came through though.', 'Reshipped a replacement unit via expedited shipping at no cost to the customer.', 'resolved', 'medium', 'payment', NULL, 'customer_3780', NULL, NULL, NULL, NULL, 'ORD-790855', '2026-08-11 03:59:32', '2026-08-21 08:59:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Product stopped working after two days', 'My USB-C hub worked fine for about two days and then just stopped turning on entirely. I''ve tried different outlets and cables, nothing works.', NULL, 'in_progress', 'high', 'damaged_item', 'Marcus Reed', 'customer_1400', NULL, NULL, NULL, NULL, 'ORD-148458', '2026-07-20 21:52:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my portable power bank has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Corrected the shipping address in our system before the label was generated; delivery proceeded normally.', 'resolved', 'high', 'shipping', 'Aisha Bello', 'customer_4185', 'FedEx', 'FE4803044105', 'lost', '2026-05-27', 'ORD-853240', '2026-05-24 01:00:32', '2026-05-31 04:00:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Partial refund amount is incorrect', 'I was refunded for my returned portable power bank but the amount is $15 less than what I paid. I still have the original order confirmation showing the full price.', NULL, 'open', 'medium', 'refund', 'Marcus Reed', 'customer_8478', NULL, NULL, NULL, NULL, 'ORD-239816', '2026-06-22 15:58:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my tablet stand.', NULL, 'resolved', 'medium', 'account', NULL, 'customer_9270', NULL, NULL, NULL, NULL, 'ORD-547470', '2026-06-11 22:34:32', '2026-06-15 09:34:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Charged twice for the same order', 'I can see two identical charges on my card for the same external SSD order placed yesterday. Only one order confirmation email came through though.', NULL, 'in_progress', 'high', 'payment', 'Priya Nair', 'customer_9540', NULL, NULL, NULL, NULL, 'ORD-608136', '2026-06-02 06:14:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Charged twice for the same order', 'I can see two identical charges on my card for the same mechanical keyboard order placed yesterday. Only one order confirmation email came through though.', NULL, 'in_progress', 'low', 'payment', 'Priya Nair', 'customer_6238', NULL, NULL, NULL, NULL, 'ORD-666390', '2026-08-11 09:22:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Product stopped working after two days', 'My gaming laptop worked fine for about two days and then just stopped turning on entirely. I''ve tried different outlets and cables, nothing works.', NULL, 'open', 'high', 'damaged_item', 'Marcus Reed', 'customer_7797', NULL, NULL, NULL, NULL, 'ORD-527398', '2026-07-09 20:02:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Unable to update saved payment method', 'I''m trying to remove an old expired card and add a new one under my payment settings, but the page just spins and never saves the change.', NULL, 'in_progress', 'high', 'account', 'Diego Torres', 'customer_1320', NULL, NULL, NULL, NULL, 'ORD-998348', '2026-06-09 01:01:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Order hasn''t arrived, tracking shows no movement', 'I ordered a noise-cancelling earbuds 9 days ago and the tracking page has shown ''label created'' with no update since. Estimated delivery date already passed. Can someone check what''s going on?', NULL, 'in_progress', 'high', 'shipping', 'Diego Torres', 'customer_9818', 'UPS', 'UP3096929657', 'delivered', '2026-06-17', 'ORD-883826', '2026-06-12 17:34:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Payment failed but amount still on hold', 'My order for a wireless headphones failed at checkout with a payment error, but my bank shows the amount as a pending hold. It''s been 5 days now.', 'Issued a full refund to the original payment method after confirming the return was received in warehouse.', 'resolved', 'medium', 'payment', NULL, 'customer_7624', NULL, NULL, NULL, NULL, 'ORD-859359', '2026-07-30 22:33:32', '2026-08-03 07:33:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Two accounts got merged, order history missing', 'Something happened during checkout and now I only see one of my two account''s order histories. My wireless headphones order from last month has disappeared from my account page.', NULL, 'open', 'medium', 'account', 'Priya Nair', 'customer_8564', NULL, NULL, NULL, NULL, 'ORD-290556', '2026-08-15 05:07:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Completely different product than what I ordered', 'I ordered a bluetooth speaker and instead received a completely unrelated item in the box. Not even close to what I purchased. Need this sorted out quickly.', 'Issued a full refund to the original payment method after confirming the return was received in warehouse.', 'resolved', 'medium', 'wrong_item', 'Diego Torres', 'customer_5558', NULL, NULL, NULL, NULL, 'ORD-888539', '2026-06-29 04:38:32', '2026-07-01 11:38:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my 27-inch monitor.', NULL, 'in_progress', 'low', 'account', 'Sarah Chen', 'customer_1659', NULL, NULL, NULL, NULL, 'ORD-890870', '2026-08-18 06:19:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Order hasn''t arrived, tracking shows no movement', 'I ordered a gaming mouse 9 days ago and the tracking page has shown ''label created'' with no update since. Estimated delivery date already passed. Can someone check what''s going on?', NULL, 'in_progress', 'low', 'shipping', NULL, 'customer_2874', 'USPS', 'US8588769565', 'delayed', '2026-07-30', 'ORD-691364', '2026-07-24 22:47:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my smartwatch three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', NULL, 'in_progress', 'low', 'refund', 'Sarah Chen', 'customer_6111', NULL, NULL, NULL, NULL, 'ORD-703766', '2026-05-27 01:06:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Item arrived with a cracked screen', 'The mechanical keyboard I ordered arrived with a visible crack across the display. The box itself looked fine on the outside, so I think it may have been packaged damaged, not damaged in transit.', 'Reshipped a replacement unit via expedited shipping at no cost to the customer.', 'closed', 'medium', 'damaged_item', NULL, 'customer_4978', NULL, NULL, NULL, NULL, 'ORD-206851', '2026-05-24 03:37:32', '2026-06-03 15:37:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Package marked delivered but never received', 'Tracking says my noise-cancelling earbuds was delivered yesterday afternoon, but there''s nothing at my door or with my neighbors. I checked all around the property. This is concerning since it''s a higher-value item.', 'Reshipped a replacement unit via expedited shipping at no cost to the customer.', 'resolved', 'medium', 'shipping', 'Priya Nair', 'customer_2129', 'DHL', 'DH9421518487', 'lost', '2026-06-07', 'ORD-630538', '2026-05-31 03:31:32', '2026-06-07 10:31:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Requesting refund instead of replacement', 'My 4K action camera arrived defective and I initially asked for a replacement, but I''ve decided I''d rather just get a refund at this point. How do I change the request?', NULL, 'open', 'high', 'refund', 'Aisha Bello', 'customer_9817', NULL, NULL, NULL, NULL, 'ORD-912270', '2026-06-20 23:04:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my tablet stand but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'in_progress', 'high', 'damaged_item', 'Sarah Chen', 'customer_5569', NULL, NULL, NULL, NULL, 'ORD-572700', '2026-07-20 22:55:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Two accounts got merged, order history missing', 'Something happened during checkout and now I only see one of my two account''s order histories. My tablet stand order from last month has disappeared from my account page.', NULL, 'open', 'medium', 'account', NULL, 'customer_3979', NULL, NULL, NULL, NULL, 'ORD-611233', '2026-07-25 01:40:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my tablet stand but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'in_progress', 'high', 'damaged_item', NULL, 'customer_5526', NULL, NULL, NULL, NULL, 'ORD-682789', '2026-08-19 21:19:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Wrong delivery address used for my order', 'I just noticed the order confirmation for my webcam has my old apartment address, not the one I updated last month. Can this be corrected before it ships, or redirected?', 'Escalated to the payment processor; duplicate charge was reversed within 3 business days.', 'resolved', 'medium', 'shipping', 'Marcus Reed', 'customer_8800', 'UPS', 'UP6339955011', 'delivered', '2026-06-24', 'ORD-777278', '2026-06-19 22:41:32', '2026-06-20 23:41:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my noise-cancelling earbuds.', 'Applied the missing discount manually and refunded the difference to the customer''s card.', 'resolved', 'critical', 'account', 'Aisha Bello', 'customer_6419', NULL, NULL, NULL, NULL, 'ORD-468900', '2026-05-23 23:14:32', '2026-05-29 03:14:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Refund never processed after return', 'I returned my bluetooth speaker three weeks ago and the tracking confirms it was received by your warehouse, but I still haven''t seen a refund on my card statement.', NULL, 'in_progress', 'low', 'refund', 'Aisha Bello', 'customer_4033', NULL, NULL, NULL, NULL, 'ORD-300845', '2026-07-24 14:01:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my USB-C hub but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'high', 'damaged_item', 'Aisha Bello', 'customer_4727', NULL, NULL, NULL, NULL, 'ORD-478411', '2026-07-30 04:31:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Feature request: order history export', 'It would be really helpful to have a way to export my order history as a CSV for my own records, especially for warranty purposes on things like my gaming mouse.', NULL, 'in_progress', 'low', 'account', 'Sarah Chen', 'customer_5786', NULL, NULL, NULL, NULL, 'ORD-831295', '2026-08-04 16:36:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Payment failed but amount still on hold', 'My order for a laptop charger failed at checkout with a payment error, but my bank shows the amount as a pending hold. It''s been 5 days now.', NULL, 'open', 'medium', 'payment', NULL, 'customer_8843', NULL, NULL, NULL, NULL, 'ORD-561865', '2026-07-09 08:28:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my smart home hub but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'high', 'damaged_item', NULL, 'customer_9056', NULL, NULL, NULL, NULL, 'ORD-177680', '2026-06-08 16:48:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Package marked delivered but never received', 'Tracking says my gaming mouse was delivered yesterday afternoon, but there''s nothing at my door or with my neighbors. I checked all around the property. This is concerning since it''s a higher-value item.', NULL, 'open', 'high', 'shipping', 'Aisha Bello', 'customer_2395', 'DHL', 'DH7539399243', 'lost', '2026-08-10', 'ORD-360247', '2026-08-05 19:43:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Received the wrong color', 'I ordered the black version of the 4K action camera but received the white one instead. Could I get the correct color sent, and how do I return the incorrect item?', NULL, 'in_progress', 'medium', 'wrong_item', 'Sarah Chen', 'customer_2625', NULL, NULL, NULL, NULL, 'ORD-899787', '2026-07-25 17:18:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my mechanical keyboard but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'low', 'damaged_item', 'Marcus Reed', 'customer_3564', NULL, NULL, NULL, NULL, 'ORD-102805', '2026-06-29 22:47:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Payment failed but amount still on hold', 'My order for a USB-C hub failed at checkout with a payment error, but my bank shows the amount as a pending hold. It''s been 5 days now.', NULL, 'open', 'low', 'payment', 'Aisha Bello', 'customer_8438', NULL, NULL, NULL, NULL, 'ORD-174637', '2026-05-26 05:32:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my bluetooth speaker but the box was missing the charging cable and manual that should have been included based on the product listing.', 'Escalated to the payment processor; duplicate charge was reversed within 3 business days.', 'resolved', 'low', 'damaged_item', 'Marcus Reed', 'customer_3441', NULL, NULL, NULL, NULL, 'ORD-378535', '2026-08-03 11:28:32', '2026-08-06 23:28:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Received the wrong color', 'I ordered the black version of the portable power bank but received the white one instead. Could I get the correct color sent, and how do I return the incorrect item?', NULL, 'open', 'medium', 'wrong_item', 'Aisha Bello', 'customer_7594', NULL, NULL, NULL, NULL, 'ORD-385470', '2026-06-17 20:00:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Charged twice for the same order', 'I can see two identical charges on my card for the same mechanical keyboard order placed yesterday. Only one order confirmation email came through though.', 'Issued a full refund to the original payment method after confirming the return was received in warehouse.', 'closed', 'low', 'payment', 'Diego Torres', 'customer_6280', NULL, NULL, NULL, NULL, 'ORD-733039', '2026-07-20 13:26:32', '2026-07-24 23:26:32');
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Missing accessories in the box', 'I received my 27-inch monitor but the box was missing the charging cable and manual that should have been included based on the product listing.', NULL, 'open', 'medium', 'damaged_item', NULL, 'customer_5557', NULL, NULL, NULL, NULL, 'ORD-290305', '2026-06-07 23:51:32', NULL);
INSERT INTO tickets (domain, title, description, resolution_notes, status, priority, category, assignee, reporter, carrier, tracking_number, shipping_status, estimated_delivery, order_id, created_at, resolved_at) VALUES ('ecommerce', 'Payment failed but amount still on hold', 'My order for a mechanical keyboard failed at checkout with a payment error, but my bank shows the amount as a pending hold. It''s been 5 days now.', NULL, 'resolved', 'medium', 'payment', 'Priya Nair', 'customer_6260', NULL, NULL, NULL, NULL, 'ORD-802685', '2026-08-08 08:10:32', '2026-08-15 19:10:32');

-- Quick sanity check after running this file:
-- SELECT category, status, COUNT(*) FROM tickets GROUP BY category, status ORDER BY category;